### ISSUE TITLE
Use MSAL 2.x + PKCE instead of MSAL 1.x + Implicit auth for fallback cases

### ISSUE THREAD

**Issue by kasturgo** [OfficeDev/Office-Addin-Taskpane-SSO#64]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [X] I am running the latest version of Node and the tools
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

# Expected behavior

Current code requires us to use MSAL 1.x and use implicit auth. However, MSAL 2.x supports PKCE which is more secure. Why are examples not updated? Any issue with using MSAL 2.x +PKCE?

# Current behavior

Current code requires us to use MSAL 1.x and use implicit auth.

**Comment by AlexJerabek** [comment]
Assigning to @davidchesnut for investigation.

**Comment by davidchesnut** [comment]
Hi @kasturgo, I believe this has been fixed since your original request. Last fall we did an update to use the [msal-browser 2.28.1 library](https://www.npmjs.com/package/%40azure/msal-browser). This is MSAL 2.0 and supports PKCE. I'll go ahead and close this issue, but please reopen if we're missing anything. 
Thank you!
